"""adicionando unique ao codigo de barras

Revision ID: 0a54ac736cf8
Revises: 56a59284e3e1
Create Date: 2025-05-23 08:30:01.079592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a54ac736cf8'
down_revision: Union[str, None] = '56a59284e3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_codigo_barras'), table_name='produtos')
    op.create_index(op.f('ix_produtos_codigo_barras'), 'produtos', ['codigo_barras'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_codigo_barras'), table_name='produtos')
    op.create_index(op.f('ix_produtos_codigo_barras'), 'produtos', ['codigo_barras'], unique=False)
    # ### end Alembic commands ###
