"""adicionando elementos nas  tabelas

Revision ID: aad7020b4d63
Revises: 6f373c0d268d
Create Date: 2025-05-23 17:12:05.063522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad7020b4d63'
down_revision: Union[str, None] = '6f373c0d268d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('nivel', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('nome', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'nome')
    op.drop_column('clientes', 'nivel')
    # ### end Alembic commands ###
