"""adicionando tabela pedido_itens

Revision ID: b0e00405ce55
Revises: e7b73e544a75
Create Date: 2025-05-23 14:12:50.220969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e00405ce55'
down_revision: Union[str, None] = 'e7b73e544a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pedidos_id_produto_fkey'), 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'id_produto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('id_produto', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('pedidos_id_produto_fkey'), 'pedidos', 'produtos', ['id_produto'], ['id'])
    # ### end Alembic commands ###
